DWAPlannerROS:
  max_vel_x: 0.35
  min_vel_x: 0.05
  max_vel_trans: 0.35
  min_vel_trans: 0.05

  max_vel_theta: 0.8
  min_vel_theta: 0.2
  min_in_place_vel_theta: 0.2

  acc_lim_x: 0.8
  acc_lim_theta: 1.5

  xy_goal_tolerance: 0.20
  yaw_goal_tolerance: 0.25
  latch_xy_goal_tolerance: false

  sim_time: 1.2
  sim_granularity: 0.025
  angular_sim_granularity: 0.025
  vx_samples: 8
  vtheta_samples: 20

  path_distance_bias: 24.0
  goal_distance_bias: 20.0
  occdist_scale: 0.20
  forward_point_distance: 0.20
  stop_time_buffer: 0.20
  scaling_speed: 0.25
  max_scaling_factor: 0.20

  oscillation_reset_dist: 0.10