// Generated by gencpp from file ris_msgs/Hello.msg
// DO NOT EDIT!


#ifndef RIS_MSGS_MESSAGE_HELLO_H
#define RIS_MSGS_MESSAGE_HELLO_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ris_msgs
{
template <class ContainerAllocator>
struct Hello_
{
  typedef Hello_<ContainerAllocator> Type;

  Hello_()
    : text()  {
    }
  Hello_(const ContainerAllocator& _alloc)
    : text(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _text_type;
  _text_type text;





  typedef boost::shared_ptr< ::ris_msgs::Hello_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ris_msgs::Hello_<ContainerAllocator> const> ConstPtr;

}; // struct Hello_

typedef ::ris_msgs::Hello_<std::allocator<void> > Hello;

typedef boost::shared_ptr< ::ris_msgs::Hello > HelloPtr;
typedef boost::shared_ptr< ::ris_msgs::Hello const> HelloConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ris_msgs::Hello_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ris_msgs::Hello_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ris_msgs::Hello_<ContainerAllocator1> & lhs, const ::ris_msgs::Hello_<ContainerAllocator2> & rhs)
{
  return lhs.text == rhs.text;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ris_msgs::Hello_<ContainerAllocator1> & lhs, const ::ris_msgs::Hello_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ris_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ris_msgs::Hello_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ris_msgs::Hello_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ris_msgs::Hello_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ris_msgs::Hello_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ris_msgs::Hello_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ris_msgs::Hello_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ris_msgs::Hello_<ContainerAllocator> >
{
  static const char* value()
  {
    return "74697ed3d931f6eede8bf3a8dfeca160";
  }

  static const char* value(const ::ris_msgs::Hello_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x74697ed3d931f6eeULL;
  static const uint64_t static_value2 = 0xde8bf3a8dfeca160ULL;
};

template<class ContainerAllocator>
struct DataType< ::ris_msgs::Hello_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ris_msgs/Hello";
  }

  static const char* value(const ::ris_msgs::Hello_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ris_msgs::Hello_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string text\n"
;
  }

  static const char* value(const ::ris_msgs::Hello_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ris_msgs::Hello_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.text);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct Hello_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ris_msgs::Hello_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ris_msgs::Hello_<ContainerAllocator>& v)
  {
    s << indent << "text: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.text);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RIS_MSGS_MESSAGE_HELLO_H
