// Generated by gencpp from file ris_msgs/PingPongResponse.msg
// DO NOT EDIT!


#ifndef RIS_MSGS_MESSAGE_PINGPONGRESPONSE_H
#define RIS_MSGS_MESSAGE_PINGPONGRESPONSE_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ris_msgs
{
template <class ContainerAllocator>
struct PingPongResponse_
{
  typedef PingPongResponse_<ContainerAllocator> Type;

  PingPongResponse_()
    : output()  {
    }
  PingPongResponse_(const ContainerAllocator& _alloc)
    : output(_alloc)  {
  (void)_alloc;
    }



   typedef std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other >  _output_type;
  _output_type output;





  typedef boost::shared_ptr< ::ris_msgs::PingPongResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ris_msgs::PingPongResponse_<ContainerAllocator> const> ConstPtr;

}; // struct PingPongResponse_

typedef ::ris_msgs::PingPongResponse_<std::allocator<void> > PingPongResponse;

typedef boost::shared_ptr< ::ris_msgs::PingPongResponse > PingPongResponsePtr;
typedef boost::shared_ptr< ::ris_msgs::PingPongResponse const> PingPongResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ris_msgs::PingPongResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ris_msgs::PingPongResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::ris_msgs::PingPongResponse_<ContainerAllocator1> & lhs, const ::ris_msgs::PingPongResponse_<ContainerAllocator2> & rhs)
{
  return lhs.output == rhs.output;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::ris_msgs::PingPongResponse_<ContainerAllocator1> & lhs, const ::ris_msgs::PingPongResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace ris_msgs

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsFixedSize< ::ris_msgs::PingPongResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ris_msgs::PingPongResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ris_msgs::PingPongResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ris_msgs::PingPongResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ris_msgs::PingPongResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ris_msgs::PingPongResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ris_msgs::PingPongResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "0825d95fdfa2c8f4bbb4e9c74bccd3fd";
  }

  static const char* value(const ::ris_msgs::PingPongResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x0825d95fdfa2c8f4ULL;
  static const uint64_t static_value2 = 0xbbb4e9c74bccd3fdULL;
};

template<class ContainerAllocator>
struct DataType< ::ris_msgs::PingPongResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ris_msgs/PingPongResponse";
  }

  static const char* value(const ::ris_msgs::PingPongResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ris_msgs::PingPongResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "string output\n"
;
  }

  static const char* value(const ::ris_msgs::PingPongResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ris_msgs::PingPongResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.output);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct PingPongResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ris_msgs::PingPongResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::ris_msgs::PingPongResponse_<ContainerAllocator>& v)
  {
    s << indent << "output: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename ContainerAllocator::template rebind<char>::other > >::stream(s, indent + "  ", v.output);
  }
};

} // namespace message_operations
} // namespace ros

#endif // RIS_MSGS_MESSAGE_PINGPONGRESPONSE_H
