// Generated by gencpp from file ris_msgs/PingPong.msg
// DO NOT EDIT!


#ifndef RIS_MSGS_MESSAGE_PINGPONG_H
#define RIS_MSGS_MESSAGE_PINGPONG_H

#include <ros/service_traits.h>


#include <ris_msgs/PingPongRequest.h>
#include <ris_msgs/PingPongResponse.h>


namespace ris_msgs
{

struct PingPong
{

typedef PingPongRequest Request;
typedef PingPongResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct PingPong
} // namespace ris_msgs


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ris_msgs::PingPong > {
  static const char* value()
  {
    return "c63e85f503b805d84df783e71c6bb0d2";
  }

  static const char* value(const ::ris_msgs::PingPong&) { return value(); }
};

template<>
struct DataType< ::ris_msgs::PingPong > {
  static const char* value()
  {
    return "ris_msgs/PingPong";
  }

  static const char* value(const ::ris_msgs::PingPong&) { return value(); }
};


// service_traits::MD5Sum< ::ris_msgs::PingPongRequest> should match
// service_traits::MD5Sum< ::ris_msgs::PingPong >
template<>
struct MD5Sum< ::ris_msgs::PingPongRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ris_msgs::PingPong >::value();
  }
  static const char* value(const ::ris_msgs::PingPongRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ris_msgs::PingPongRequest> should match
// service_traits::DataType< ::ris_msgs::PingPong >
template<>
struct DataType< ::ris_msgs::PingPongRequest>
{
  static const char* value()
  {
    return DataType< ::ris_msgs::PingPong >::value();
  }
  static const char* value(const ::ris_msgs::PingPongRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ris_msgs::PingPongResponse> should match
// service_traits::MD5Sum< ::ris_msgs::PingPong >
template<>
struct MD5Sum< ::ris_msgs::PingPongResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ris_msgs::PingPong >::value();
  }
  static const char* value(const ::ris_msgs::PingPongResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ris_msgs::PingPongResponse> should match
// service_traits::DataType< ::ris_msgs::PingPong >
template<>
struct DataType< ::ris_msgs::PingPongResponse>
{
  static const char* value()
  {
    return DataType< ::ris_msgs::PingPong >::value();
  }
  static const char* value(const ::ris_msgs::PingPongResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // RIS_MSGS_MESSAGE_PINGPONG_H
